In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
data = pd.read_csv("insurance.csv")

In [3]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
le=preprocessing.LabelEncoder()

In [5]:
a=le.fit(data['smoker'])
a

LabelEncoder()

In [6]:
data['smoker']=le.transform(data['smoker'])

In [7]:
data.head()

age     sex     bmi  children  smoker     region      charges
0   19  female  27.900         0       1  southwest  16884.92400
1   18    male  33.770         1       0  southeast   1725.55230
2   28    male  33.000         3       0  southeast   4449.46200
3   33    male  22.705         0       0  northwest  21984.47061
4   32    male  28.880         0       0  northwest   3866.85520

In [8]:
d=pd.get_dummies(data)
d.head(10)

age     bmi  children  smoker      charges  sex_female  sex_male  \
0   19  27.900         0       1  16884.92400           1         0   
1   18  33.770         1       0   1725.55230           0         1   
2   28  33.000         3       0   4449.46200           0         1   
3   33  22.705         0       0  21984.47061           0         1   
4   32  28.880         0       0   3866.85520           0         1   
5   31  25.740         0       0   3756.62160           1         0   
6   46  33.440         1       0   8240.58960           1         0   
7   37  27.740         3       0   7281.50560           1         0   
8   37  29.830         2       0   6406.41070           0         1   
9   60  25.840         0       0  28923.13692           1         0   

   region_northeast  region_northwest  region_southeast  region_southwest  
0                 0                 0                 0                 1  
1                 0                 0                 1                 0  
2                 0                 0                 1                 0  
3                 0                 1                 0                 0  
4                 0                 1                 0                 0  
5                 0                 0                 1                 0  
6                 0                 0                 1                 0  
7                 0                 1                 0                 0  
8                 1                 0                 0                 0  
9                 0                 1                 0                 0

In [9]:
correlation=d.corr('pearson')
abs(correlation['charges']).sort_values()

region_northeast    0.006349
region_northwest    0.039905
region_southwest    0.043210
sex_male            0.057292
sex_female          0.057292
children            0.067998
region_southeast    0.073982
bmi                 0.198341
age                 0.299008
smoker              0.787251
charges             1.000000
Name: charges, dtype: float64

In [10]:
x = np.array(d[['bmi','children','age','smoker']])
y = np.array(d['charges'])
y=y.reshape(-1,1)

In [11]:
scaler=MinMaxScaler()

In [12]:
X=scaler.fit_transform(x)
Y=scaler.fit_transform(y)

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.3)

In [14]:
xtrain.size

3744

In [15]:
ytrain

array([[1.53104413e-01],
       [9.97612505e-02],
       [1.63368288e-01],
       [7.26905340e-01],
       [1.19451881e-01],
       [6.04089879e-02],
       [8.88218009e-02],
       [1.82537834e-01],
       [5.43557485e-02],
       [0.00000000e+00],
       [1.17096782e-01],
       [1.60670632e-01],
       [4.64554504e-02],
       [2.76712476e-02],
       [7.96583276e-02],
       [8.67250095e-02],
       [3.91978792e-01],
       [2.24535110e-04],
       [1.77942092e-01],
       [2.08922013e-01],
       [2.30385442e-01],
       [1.92161019e-03],
       [4.88953663e-02],
       [7.22736728e-02],
       [3.50544107e-01],
       [1.00550136e-01],
       [8.28443397e-02],
       [5.71261933e-01],
       [2.23445061e-03],
       [1.03779635e-01],
       [6.00564239e-01],
       [3.65283785e-02],
       [7.55648501e-02],
       [1.72687473e-02],
       [8.66720115e-02],
       [9.67158953e-03],
       [6.04589725e-01],
       [1.65016993e-02],
       [2.44682755e-01],
       [1.02401246e-01],


In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
regressor = LinearRegression()

In [18]:
regressor.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
y_pred =regressor.predict(xtest)

In [20]:
y_pred

array([[ 1.03122204e-02],
       [ 6.29274329e-02],
       [ 2.34516799e-01],
       [ 4.87835840e-01],
       [ 4.84827926e-01],
       [ 9.78214481e-02],
       [ 1.73068044e-01],
       [ 1.91214447e-01],
       [-2.55854755e-03],
       [ 1.58574847e-01],
       [ 1.12520765e-01],
       [ 1.39812109e-01],
       [ 4.71408259e-01],
       [ 6.17850936e-01],
       [ 1.12329637e-01],
       [ 1.23917950e-01],
       [ 1.44658082e-01],
       [ 1.83163665e-01],
       [ 2.09504989e-01],
       [ 1.43020001e-01],
       [ 1.66705989e-01],
       [ 1.67500754e-02],
       [ 1.51011079e-01],
       [ 4.54937702e-01],
       [ 1.28313146e-01],
       [ 1.28939121e-01],
       [ 6.36763788e-01],
       [ 1.63604000e-01],
       [ 7.58445994e-02],
       [-7.91429954e-03],
       [ 8.42417491e-03],
       [ 1.49855764e-01],
       [ 5.33326096e-02],
       [ 4.75063020e-01],
       [ 1.61469647e-01],
       [ 1.45628957e-02],
       [ 4.22775066e-01],
       [ 1.08537234e-01],
       [ 4.8

In [21]:
for i in zip(y_pred,ytest):
    print(i)

(array([0.01031222]), array([0.01722238]))
(array([0.06292743]), array([0.09276141]))
(array([0.2345168]), array([0.23129535]))
(array([0.48783584]), array([0.32782969]))
(array([0.48482793]), array([0.32286191]))
(array([0.09782145]), array([0.14157013]))
(array([0.17306804]), array([0.11177488]))
(array([0.19121445]), array([0.21167025]))
(array([-0.00255855]), array([0.00628061]))
(array([0.15857485]), array([0.13565288]))
(array([0.11252076]), array([0.05105524]))
(array([0.13981211]), array([0.35820687]))
(array([0.47140826]), array([0.55988244]))
(array([0.61785094]), array([0.75653285]))
(array([0.11232964]), array([0.08414767]))
(array([0.12391795]), array([0.43446039]))
(array([0.14465808]), array([0.15702607]))
(array([0.18316366]), array([0.19026851]))
(array([0.20950499]), array([0.20308407]))
(array([0.14302]), array([0.14738995]))
(array([0.16670599]), array([0.07399276]))
(array([0.01675008]), array([0.00210798]))
(array([0.15101108]), array([0.11838126]))
(array([0.4549

(array([0.10565943]), array([0.18010001]))
(array([0.19791067]), array([0.19644765]))
(array([0.1705495]), array([0.18368008]))
(array([0.49809619]), array([0.32086617]))
(array([0.43720918]), array([0.27334424]))
(array([-0.00621116]), array([0.00940409]))
(array([-0.00010036]), array([0.00937056]))
(array([0.57762052]), array([0.44289594]))
(array([0.20925395]), array([0.14532515]))
(array([0.0916926]), array([0.06624737]))
(array([0.04949232]), array([0.0278413]))
(array([0.16242526]), array([0.14286333]))
(array([0.40369171]), array([0.26539531]))
(array([0.06539723]), array([0.00658324]))
(array([0.10381627]), array([0.06786255]))
(array([0.16013584]), array([0.08382769]))
(array([0.07566249]), array([0.05153575]))
(array([0.08316721]), array([0.06853769]))
(array([0.07146485]), array([0.04398235]))
(array([0.5288125]), array([0.3680701]))
(array([-0.00601962]), array([0.17178648]))
(array([0.17663625]), array([0.10098445]))
(array([0.43318571]), array([0.53724689]))
(array([0.053

In [22]:
from sklearn.metrics import mean_squared_error,r2_score

In [23]:
mean_squared_error(ytest,y_pred)

0.008400424662965282

In [24]:
r2_score(ytest,y_pred)

0.7614266127173215